#Sets the server you wish to connect do when doing /hub or /lobby
TargetServer: "lobby"

#Customizes the messages sent while doing /hub or /lobby
ConnectingMessage: "&aSending you to Lobby.."
AlreadyOnHubMessage: "&cYou are already connected to this server!"
CannotExecuteOnConsoleMessage: "&cThis command can only be executed by a player!"
ServerNotFound: "&cIt appears that the server you are trying to connect to does not exist. Please contact an Administrator."
NoPermission: "&cYou do not have permission to run this command!"
ReloadedPlugin: "&aSuccessfully reloaded SlashHub!"

#Permissions
#/Hub permission: slashhub.use
#/HubReload permission: slashhubreload