#################################
#    SlashHub Version 1.8       #
#################################

# PLEASE PRIVATE MESSAGE SKYGAMEZ OR LEAVE A POST IN THE DISCUSSION TAB BEFORE RATING ONE STAR!
# YOUR ISSUE MIGHT BE AN EASY FIX!!

#Permissions
#/Hub (including custom aliases) permission: slashhub.use
#/HubReload permission: slashhub.reload


# Target server selection
# Note that the server(s) you put in MUST be a server that is defined in the servers part of your bungeecord config

# Set your lobbys according to the lobbies defined servername in your bungeecord config
# You can set more than 2 lobbies!
TargetServers:
  - "lobby1"
  - "lobby2"

# This sets the command aliases for the Hub command
# A RESTART IS REQUIRED TO COMMIT CHANGES TO THIS!
CommandAliases:
  - "lobby"

# Message customization
# MiniMessage is supported. See the MiniMessage Format Wiki for more info: https://docs.advntr.dev/minimessage/format.html
Messages:
  ConnectingMessage: "<green>Sending you to the Lobby.."
  AlreadyOnHubMessage: "<red>You are already connected to the hub!"
  CannotExecuteOnConsoleMessage: "<red>You cannot execute this command from console!"
  ServerNotFound: "<red>The server you attempted to connect to could not be found. Please contact an administrator."
  NoPermission: "<red>You do not have permission to run this command!"
  ReloadedPlugin: "<green>Successfully reloaded SlashHub!"


#Do not touch this
Config-Version: 1.0