#################################
#     SlashHub Version 1.11     #
#################################

# Need assistance? Have a request? Found a bug?
# Join our support Discord for help!

# Permissions
#   slashhub.use - Allows usage of /hub and its according aliases - can be disabled
#   slashhub.admin.reload - Allows usage of /hubreload
#   slashhub.admin.* - Grants access to every admin command
#   slashhub.bypass - Allows bypassing of /hub being disabled on select servers.


# Target server selection
# Note that the server(s) you put in MUST be a server that is defined in the servers part of your BungeeCord config

# Set your lobby's according to the lobbies defined server name in your BungeeCord config
# You can set more than 1 lobby!
TargetServers:
  - "lobby"

# Set servers you want to block access to /hub
# You can set more than 1 server!
DisabledServers:
  - "example"

# This sets the command aliases for the Hub command
# A RESTART IS REQUIRED TO COMMIT CHANGES TO THIS!
CommandAliases:
  - "lobby"

# Message customization
# MiniMessage is supported. See the MiniMessage Format Wiki for more info: https://docs.advntr.dev/minimessage/format.html
# --IMPORTANT-- HEXCODES DO NOT WORK ON VERSIONS UNDER 1.16!

Messages:
  ConnectingMessage: "<green>Sending you to the Lobby.."
  AlreadyOnHubMessage: "<red>You are already connected to the hub!"
  CannotExecuteOnConsoleMessage: "<red>You cannot execute this command from console!"
  ServerNotFound: "<red>The server you attempted to connect to could not be found. Please contact an administrator."
  NoPermission: "<red>You do not have permission to run this command!"
  ReloadedPlugin: "<green>Successfully reloaded SlashHub!"
  ServerDisabled: "<red>This command is disabled on this server!"

# Set this to false if you would like /hub to not be permission bound
# A RESTART IS REQUIRED TO COMMIT CHANGES TO THIS!
RequireUsePermission: true


#Do not touch this
Config-Version: 1.1